//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stomatology.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnozi
    {
        public int ID_Diagnoza { get; set; }
        public string Nazvanie_Diagnoza { get; set; }
    }
}
