//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stomatology.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uslugi()
        {
            this.Zapisi = new HashSet<Zapisi>();
        }
    
        public int ID_Uslugi { get; set; }
        public string Nazvanie_Uslugi { get; set; }
        public Nullable<decimal> Stoimost_Uslugi { get; set; }
        public Nullable<int> ID_Tipa_Uslugi { get; set; }
        public byte[] ImageUsl { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> ID_Specialnosti { get; set; }
    
        public virtual Specialnosti Specialnosti { get; set; }
        public virtual Tip_uslugi Tip_uslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapisi> Zapisi { get; set; }
    }
}
