//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stomatology.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisi
    {
        public int ID_Zapisi { get; set; }
        public Nullable<int> Pacient { get; set; }
        public Nullable<int> Vrach { get; set; }
        public Nullable<System.DateTime> Date_priema { get; set; }
        public Nullable<int> ID_Uslugi { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
